# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'FSnetWorkTools_AFN' do

pod ‘AFNetworking’

end

target 'FSnetWorkTools_AFNTests' do

end

target 'FSnetWorkTools_AFNUITests' do

end

